version: 2.1

jobs:

  test:
    docker:
      - image: cimg/node:20.10

    steps:
      - checkout

      - restore_cache:
          keys:
            - node-cache-{{ checksum "package-lock.json" }}

      - run:
          name: Install Dependencies
          command: npm ci

      - save_cache:
          key: node-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - run:
          name: Run Unit Tests
          command: npm test

  docker-build-and-push:
    machine: true

    steps:
      - checkout

      - run:
          name: Build Docker Image
          command: |
            docker build -t $DOCKER_USERNAME/simple-ci-cd-app:latest .

      - run:
          name: Docker Login
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - run:
          name: Push Docker Image
          command: |
            docker push $DOCKER_USERNAME/simple-ci-cd-app:latest

workflows:
  version: 2

  ci_pipeline:
    jobs:
      - test

      - docker-build-and-push:
          requires:
            - test
