version: 2.1

jobs:

  lint:
    docker:
      - image: -cimg/node:20.19-browsers

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: npm ci

      - run:
          name: Run ESLint
          command: npm run lint


  sast-scan:
    docker:
      - image: returntocorp/semgrep

    steps:
      - checkout

      - run:
          name: Run Semgrep SAST Scan
          command: |
            semgrep --config=auto .


  test:
    docker:
      - image: cimg/node:20.10

    steps:
      - checkout

      - restore_cache:
          keys:
            - node-cache-{{ checksum "package-lock.json" }}

      - run:
          name: Install Dependencies
          command: npm ci

      - save_cache:
          key: node-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - run:
          name: Run Unit Tests
          command: npm test


  docker-build:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: true

    steps:
      - checkout

      - run:
          name: Build Docker Image
          command: |
            docker build -t simple-ci-cd-app:latest .


  trivy-scan:
    docker:
      - image: aquasec/trivy:latest

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Build Docker Image
          command: |
            docker build -t simple-ci-cd-app:latest .

      - run:
          name: Scan Docker Image
          command: |
            trivy image \
            --severity HIGH,CRITICAL \
            --exit-code 1 \
            simple-ci-cd-app:latest


  docker-push:
    machine:
      image: ubuntu-2204:current

    steps:
      - checkout

      - run:
          name: Build Docker Image
          command: |
            docker build -t $DOCKER_USERNAME/simple-ci-cd-app:latest .

      - run:
          name: Docker Login
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - run:
          name: Push Docker Image
          command: |
            docker push $DOCKER_USERNAME/simple-ci-cd-app:latest


workflows:
  version: 2

  secure_pipeline:
    jobs:
      - lint

      - sast-scan:
          requires:
            - lint

      - test:
          requires:
            - sast-scan

      - docker-build:
          requires:
            - test

      - trivy-scan:
          requires:
            - docker-build

      - docker-push:
          requires:
            - trivy-scan
